dist: trusty

language: node_js

node_js:
  - "node"
  - "lts/*"

addons:
  chrome: stable

before_install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &

script:
  - npm run test-ci

after_success:
  - npm run coverage
